#!/bin/sh
# Version: v.23.08.03

set -e

export LIBRARIES_REPOSITORIES='https://github.com/sunflowerit/waftlib.git'
# Libraries version branches: v.21.05.10, v.21.09.22, v.22.05.30, v.23.08.03
export LIBRARIES_VERSION_BRANCH="${LIBRARIES_VERSION_BRANCH:-v.23.08.03}"

################################################################
######                                                    ######
######       Don't change variables after this line       ######
######                                                    ######
################################################################

SCRIPT_PATH="$(cd "$(/usr/bin/dirname "${0}")" && /bin/pwd)"
ODOO_WORK_DIR="$(cd "${SCRIPT_PATH}" && /bin/pwd)"
cd "${ODOO_WORK_DIR}"

/bin/echo "( INFO ) : Remove exist ${ODOO_WORK_DIR}/.ignore/waftlib"
/bin/rm -fr "${ODOO_WORK_DIR}/.ignore/waftlib" && \
/bin/mkdir -p "${ODOO_WORK_DIR}/.ignore/waftlib"
/bin/echo "( INFO ) : Clone ${LIBRARIES_REPOSITORIES} to ${ODOO_WORK_DIR}/.ignore/waftlib"
/usr/bin/git clone -b "${LIBRARIES_VERSION_BRANCH}" "${LIBRARIES_REPOSITORIES}" "${ODOO_WORK_DIR}/.ignore/waftlib" 2> /dev/null || \
/usr/bin/git clone -b master "${LIBRARIES_REPOSITORIES}" "${ODOO_WORK_DIR}/.ignore/waftlib"

/bin/echo "( INFO ) : Run ${ODOO_WORK_DIR}/.ignore/waftlib/bootstrap script"
"${ODOO_WORK_DIR}/.ignore/waftlib/bootstrap"
