#!/usr/bin/env bash

if ! test -f etc/odoo.template.cfg; then
    echo "Error: $(basename -- "$0") should be run from root project folder."
    exit 1
fi

. env/bin/activate

cfg=etc/odoo.cfg
if test -f "$basedir"/parts/odoo/odoo-bin; then
    odoo=parts/odoo/odoo-bin
else
    odoo=parts/odoo/odoo.py
fi

if ! test -f "$odoo" || ! test -f "$cfg" ; then
    echo "Installation not built yet! Run bin/build"
    exit 1
fi

# If we're running a subcommand that has to be the first argument, prepending
# a -c option will break it. So check whether the first argument looks like
# an option.
case $1 in
    -* | '')
        exec python "$odoo" -c "$cfg" "$@"
        ;;
    *)
        first=$1
        shift
        exec python "$odoo" "$first" -c "$cfg" "$@"
        ;;
esac
